import Head from 'next/head'
import Transaction from "../components/Transaction";
import {useWallet} from "@solana/wallet-adapter-react";
import {Heading} from "@chakra-ui/react";
import NavBar from "../components/NavBar";

export default function Home() {
  const wallet = useWallet();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      {
        wallet.connected ?
          <>
            <Heading>Start adding an instruction</Heading>
            <Transaction/>
          </> :
          <Heading>Connect your wallet</Heading>
      }
    </>
  )
}
